langage: cpp
compiler: gcc

addons:
 sonarcloud: true

before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install criterion-dev -y
  - sudo apt-get install gcovr -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90


jobs:
  include:
  - stage: Unit Tests
    script: 
      - make tests_run
  - stage: Unit Tests & Sonar
    if: (NOT type IN (pull_request)) AND (branch = master)
    script:
      - make tests_run
      - gcovr -r . -x --object-directory=. > report.xml
      - sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.login=$SONAR_TOKEN -X

env:
 global:
 - secure: 929cb6f02ea19723609b6a8bab48206fbdf1fee7

 - SONAR_HOST_URL=http://91.121.150.220:9000